# params settings
params:

# logging settings
logging:
  config: classpath:config/logback-spring.xml
  log-dir: /vdata/var/logs/dataroute/

# mybatis settings
mybatis:
  check-config-location: true
  config-location: classpath:config/mybatis-config.xml

# spring settings
spring:
  application:
    name: dataroute
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.164.113:3306/lk?characterEncoding=UTF-8
    username: root
    password: admin

# server settings
server:
  port: 8080
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: utf-8
    max-threads: 0
